# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: snapcast-client
version: beta
slug: snapcastclient
description: Snapcast client
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: "https://github.com/SimpleUserHA/hassio-addons-snapcast/tree/master/snapclient"
startup: services
boot: auto
audio: true
#somewhereelse
host_network: true
panel_icon: "mdi:cast-audio"
privileged:
  - SYS_ADMIN
init: false
#end somewhere else

#map:
#  - share:rw
options:
  log_level: info
  snapclientopts: "-h snapcastserver"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  snapclientopts: str
