# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: snapcast-client
version: 0.1.0
slug: snapcastclient
description: Snapcast client
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: "https://github.com/SimpleUserHA/hassio-addons-snapcast/tree/master/snapclient"
startup: services
boot: auto
audio: true
init: false
options:
  log_level: info
  snapclientopts: "-h snapcastserver"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  snapclientopts: str
